# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_as_email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('target_website', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='USD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EURUSD', models.FloatField()),
                ('GBPUSD', models.FloatField()),
                ('USDJPY', models.FloatField()),
                ('USDCAD', models.FloatField()),
                ('USDCHF', models.FloatField()),
                ('AUDUSD', models.FloatField()),
                ('NZDUSD', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
