# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject_fxalarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycredentials',
            name='target_website',
            field=models.URLField(),
        ),
    ]
